[build-system]
requires = ["setuptools", "wheel", "Cython"]

[project]
name = 'bencode2'
readme = 'readme.md'
version = '0.0.2'
authors = [{ name = 'trim21', email = 'trim21.me@gmail.com' }]
description = 'bencode serialize/deserialize library'
