name: Reusable workflow example

on:
  workflow_call:

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: 'wheels-sdist'
        path: dist/*.tar.gz

  build_wheel_py3_none:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: "pip" # caching pip dependencies

      - run: pip install -r requirements.txt

      - run: pip wheel . --wheel-dir=wheelhouse
        env:
          BENCODE2_NO_MYPYC: '1'

      - uses: actions/upload-artifact@v4
        with:
          name: 'wheels-py3_none'
          path: ./wheelhouse/*.whl

  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        include:
          - { os: macos-12, arch: x86_64, build: "*" } # cpython
          - { os: macos-12, arch: arm64, build: "*" }
          - { os: windows-latest, arch: x86, build: "*" }
          - { os: windows-latest, arch: AMD64, build: "*" }
          - { os: ubuntu-latest, arch: x86_64, build: "*" }
    steps:
      - uses: docker/setup-qemu-action@v3
        if: matrix.os == 'ubuntu-latest'

      - uses: actions/checkout@v4

      - name: Restore cached Primes
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\pypa\cibuildwheel\Cache
            ~/Library/Caches/cibuildwheel
            ~/.cache/cibuildwheel
          key: 'cibuildwheel-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.build }}'
          restore-keys: |
            cibuildwheel-${{ runner.os }}-${{ matrix.arch }}

      - uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_SKIP: 'pp*'

      - run: ls ./wheelhouse/

      - uses: actions/upload-artifact@v4
        with:
          name: 'wheels-${{ runner.os }}-${{ matrix.arch }}-${{ strategy.job-index }}'
          path: ./wheelhouse/*.whl

  merge-wheel-artifact:
    runs-on: ubuntu-latest
    needs: [ 'build_wheel_py3_none', 'build_wheels', 'make_sdist' ]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheel
          pattern: wheels-*

  check_dist:
    name: Check dist
    needs: [ merge-wheel-artifact ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist

      - run: pipx run twine check --strict dist/*
