name: Build Wheels

on:
  push:

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true  # Optional, use if you have submodules

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4.3.1
      with:
        path: dist/*.tar.gz

  build_wheels:
    name: Build ${{ matrix.platform }} wheels
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: 'wheel-${{ matrix.platform }}'
          path: wheelhouse/*.whl

  merge-wheel-artifact:
    runs-on: ubuntu-latest
    needs: ['build_wheels']
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheel
          pattern: wheel-*

  check_dist:
    name: Check dist
    needs: [make_sdist, merge-wheel-artifact]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.4
        with:
          name: wheel
          path: dist

      - run: pipx run twine check --strict dist/*
