name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/_build_wheels.yaml

  pypi:
    name: Upload wheels to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.8.14
